server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;

    location / {
        index index.html index.htm;
        # Esto es vital para React Router: redirige todo al index.html
        try_files $uri $uri/ /index.html;
    }

    # Opcional: Cache para archivos estáticos
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg)$ {
        expires 30d;
        add_header Cache-Control "public, no-transform";
    }

    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}
